name: MyPlugin
main: com.github.Taoist_Yu.MyPlugin.MyPlugin
version: 1.0.0

commands:
  testCommand:
    description: This is a demo command.
    usage: /<command>
    permission: <plugin name>.basic
    permission-message: You don't have <permission></source> </code> </blockquote> 
    
commands:
  fireBall:
    description: This is a demo command.
    usage: /fireBall <Player> 
    permission: <plugin name>.basic
    permission-message: You don't have <permission></source> </code> </blockquote> 
    